#include "stm32f1xx_hal.h"
#include "cmsis_os.h"
#include <string.h>

#define LED_STEP_1_PORT		GPIOA
#define LED_STEP_1_PIN		GPIO_PIN_4
#define LED_STEP_2_PORT		GPIOA
#define LED_STEP_2_PIN		GPIO_PIN_5
#define LED_STEP_3_PORT		GPIOA
#define LED_STEP_3_PIN		GPIO_PIN_6
#define LED_STEP_4_PORT		GPIOA
#define LED_STEP_4_PIN		GPIO_PIN_7
#define LED_STEP_5_PORT		GPIOC
#define LED_STEP_5_PIN		GPIO_PIN_4

#define LED_ERR_1_PORT		GPIOA
#define LED_ERR_1_PIN		GPIO_PIN_3
#define LED_ERR_2_PORT		GPIOC
#define LED_ERR_2_PIN		GPIO_PIN_5
#define LED_ERR_3_PORT		GPIOB
#define LED_ERR_3_PIN		GPIO_PIN_2
#define LED_ERR_4_PORT		GPIOB
#define LED_ERR_4_PIN		GPIO_PIN_1
#define LED_ERR_5_PORT		GPIOB
#define LED_ERR_5_PIN		GPIO_PIN_0

#define LED_STEP_1_ON		HAL_GPIO_WritePin(LED_STEP_1_PORT, LED_STEP_1_PIN, GPIO_PIN_SET)
#define LED_STEP_1_OFF		HAL_GPIO_WritePin(LED_STEP_1_PORT, LED_STEP_1_PIN, GPIO_PIN_RESET)
#define LED_STEP_2_ON		HAL_GPIO_WritePin(LED_STEP_2_PORT, LED_STEP_2_PIN, GPIO_PIN_SET)
#define LED_STEP_2_OFF		HAL_GPIO_WritePin(LED_STEP_2_PORT, LED_STEP_2_PIN, GPIO_PIN_RESET)
#define LED_STEP_3_ON		HAL_GPIO_WritePin(LED_STEP_3_PORT, LED_STEP_3_PIN, GPIO_PIN_SET)
#define LED_STEP_3_OFF		HAL_GPIO_WritePin(LED_STEP_3_PORT, LED_STEP_3_PIN, GPIO_PIN_RESET)
#define LED_STEP_4_ON		HAL_GPIO_WritePin(LED_STEP_4_PORT, LED_STEP_4_PIN, GPIO_PIN_SET)
#define LED_STEP_4_OFF		HAL_GPIO_WritePin(LED_STEP_4_PORT, LED_STEP_4_PIN, GPIO_PIN_RESET)
#define LED_STEP_5_ON		HAL_GPIO_WritePin(LED_STEP_5_PORT, LED_STEP_5_PIN, GPIO_PIN_SET)
#define LED_STEP_5_OFF		HAL_GPIO_WritePin(LED_STEP_5_PORT, LED_STEP_5_PIN, GPIO_PIN_RESET)

#define LED_ERR_1_ON		HAL_GPIO_WritePin(LED_ERR_1_PORT, LED_ERR_1_PIN, GPIO_PIN_SET)
#define LED_ERR_1_OFF		HAL_GPIO_WritePin(LED_ERR_1_PORT, LED_ERR_1_PIN, GPIO_PIN_RESET)
#define LED_ERR_2_ON		HAL_GPIO_WritePin(LED_ERR_2_PORT, LED_ERR_2_PIN, GPIO_PIN_SET)
#define LED_ERR_2_OFF		HAL_GPIO_WritePin(LED_ERR_2_PORT, LED_ERR_2_PIN, GPIO_PIN_RESET)
#define LED_ERR_3_ON		HAL_GPIO_WritePin(LED_ERR_3_PORT, LED_ERR_3_PIN, GPIO_PIN_SET)
#define LED_ERR_3_OFF		HAL_GPIO_WritePin(LED_ERR_3_PORT, LED_ERR_3_PIN, GPIO_PIN_RESET)
#define LED_ERR_4_ON		HAL_GPIO_WritePin(LED_ERR_4_PORT, LED_ERR_4_PIN, GPIO_PIN_SET)
#define LED_ERR_4_OFF		HAL_GPIO_WritePin(LED_ERR_4_PORT, LED_ERR_4_PIN, GPIO_PIN_RESET)
#define LED_ERR_5_ON		HAL_GPIO_WritePin(LED_ERR_5_PORT, LED_ERR_5_PIN, GPIO_PIN_SET)
#define LED_ERR_5_OFF		HAL_GPIO_WritePin(LED_ERR_5_PORT, LED_ERR_5_PIN, GPIO_PIN_RESET)



/*
 * 7-seg indication outputs
 */
#define IND_A_PORT			GPIOA
#define IND_A_PIN			GPIO_PIN_15
#define IND_B_PORT			GPIOC
#define IND_B_PIN			GPIO_PIN_10
#define IND_C_PORT			GPIOB
#define IND_C_PIN			GPIO_PIN_3
#define IND_D_PORT			GPIOC
#define IND_D_PIN			GPIO_PIN_12
#define IND_E_PORT			GPIOC
#define IND_E_PIN			GPIO_PIN_11
#define IND_F_PORT			GPIOA
#define IND_F_PIN			GPIO_PIN_8
#define IND_G_PORT			GPIOC
#define IND_G_PIN			GPIO_PIN_9
#define IND_DP_PORT			GPIOB
#define IND_DP_PIN			GPIO_PIN_4

#define IND_DIG_1_PORT			GPIOB
#define IND_DIG_1_PIN			GPIO_PIN_5
#define IND_DIG_2_PORT			GPIOB
#define IND_DIG_2_PIN			GPIO_PIN_6


#define IND_A_ON		HAL_GPIO_WritePin(IND_A_PORT, IND_A_PIN, GPIO_PIN_SET)
#define IND_A_OFF		HAL_GPIO_WritePin(IND_A_PORT, IND_A_PIN, GPIO_PIN_RESET)
#define IND_B_ON		HAL_GPIO_WritePin(IND_B_PORT, IND_B_PIN, GPIO_PIN_SET)
#define IND_B_OFF		HAL_GPIO_WritePin(IND_B_PORT, IND_B_PIN, GPIO_PIN_RESET)
#define IND_C_ON		HAL_GPIO_WritePin(IND_C_PORT, IND_C_PIN, GPIO_PIN_SET)
#define IND_C_OFF		HAL_GPIO_WritePin(IND_C_PORT, IND_C_PIN, GPIO_PIN_RESET)
#define IND_D_ON		HAL_GPIO_WritePin(IND_D_PORT, IND_D_PIN, GPIO_PIN_SET)
#define IND_D_OFF		HAL_GPIO_WritePin(IND_D_PORT, IND_D_PIN, GPIO_PIN_RESET)
#define IND_E_ON		HAL_GPIO_WritePin(IND_E_PORT, IND_E_PIN, GPIO_PIN_SET)
#define IND_E_OFF		HAL_GPIO_WritePin(IND_E_PORT, IND_E_PIN, GPIO_PIN_RESET)
#define IND_F_ON		HAL_GPIO_WritePin(IND_F_PORT, IND_F_PIN, GPIO_PIN_SET)
#define IND_F_OFF		HAL_GPIO_WritePin(IND_F_PORT, IND_F_PIN, GPIO_PIN_RESET)
#define IND_G_ON		HAL_GPIO_WritePin(IND_G_PORT, IND_G_PIN, GPIO_PIN_SET)
#define IND_G_OFF		HAL_GPIO_WritePin(IND_G_PORT, IND_G_PIN, GPIO_PIN_RESET)
#define IND_DP_ON		HAL_GPIO_WritePin(IND_DP_PORT, IND_DP_PIN, GPIO_PIN_SET)
#define IND_DP_OFF		HAL_GPIO_WritePin(IND_DP_PORT, IND_DP_PIN, GPIO_PIN_RESET)

#define IND_DIG_1_ON		HAL_GPIO_WritePin(IND_DIG_1_PORT, IND_DIG_1_PIN, GPIO_PIN_SET)
#define IND_DIG_1_OFF		HAL_GPIO_WritePin(IND_DIG_1_PORT, IND_DIG_1_PIN, GPIO_PIN_RESET)
#define IND_DIG_2_ON		HAL_GPIO_WritePin(IND_DIG_2_PORT, IND_DIG_2_PIN, GPIO_PIN_SET)
#define IND_DIG_2_OFF		HAL_GPIO_WritePin(IND_DIG_2_PORT, IND_DIG_2_PIN, GPIO_PIN_RESET)
/*
 * button inputs
 */
#define BTN_UP_PORT			GPIOC
#define BTN_UP_PIN			GPIO_PIN_0
#define BTN_DOWN_PORT		GPIOC
#define BTN_DOWN_PIN		GPIO_PIN_2
#define BTN_1_PORT			GPIOC
#define BTN_1_PIN			GPIO_PIN_1
#define BTN_2_PORT			GPIOC
#define BTN_2_PIN			GPIO_PIN_1

/*
 * valves output
 */
#define VALVE_UP_PORT			GPIOA
#define VALVE_UP_PIN			GPIO_PIN_1
#define VALVE_DOWN_PORT			GPIOA
#define VALVE_DOWN_PIN			GPIO_PIN_2

#define VALVE_UP_ON				HAL_GPIO_WritePin(VALVE_UP_PORT, VALVE_UP_PIN, GPIO_PIN_SET)
#define VALVE_UP_OFF			HAL_GPIO_WritePin(VALVE_UP_PORT, VALVE_UP_PIN, GPIO_PIN_RESET)
#define VALVE_DOWN_ON			HAL_GPIO_WritePin(VALVE_DOWN_PORT, VALVE_DOWN_PIN, GPIO_PIN_SET)
#define VALVE_DOWN_OFF			HAL_GPIO_WritePin(VALVE_DOWN_PORT, VALVE_DOWN_PIN, GPIO_PIN_RESET)

/*
 * RS485 address inputs
 */
#define ADDR_0_PORT			GPIOB
#define ADDR_0_PIN			GPIO_PIN_7
#define ADDR_1_PORT			GPIOB
#define ADDR_1_PIN			GPIO_PIN_8
#define ADDR_2_PORT			GPIOB
#define ADDR_2_PIN			GPIO_PIN_9
#define ADDR_3_PORT			GPIOC
#define ADDR_3_PIN			GPIO_PIN_13
#define ADDR_4_PORT			GPIOC
#define ADDR_4_PIN			GPIO_PIN_14
#define ADDR_5_PORT			GPIOC
#define ADDR_5_PIN			GPIO_PIN_15
/*
 * RS-485 config
 */
#define MODBUS_DIR_PORT		GPIOA
#define MODBUS_DIR_PIN		GPIO_PIN_11

#define MODBUS_MODE_RX			HAL_GPIO_WritePin(MODBUS_DIR_PORT, MODBUS_DIR_PIN, GPIO_PIN_RESET)
#define MODBUS_MODE_TX			HAL_GPIO_WritePin(MODBUS_DIR_PORT, MODBUS_DIR_PIN, GPIO_PIN_SET)

#define DELAY_AFTER_ALIGNING_MS		120000 //10 min
#define CHECKING_DELAY_MS			60000 // 1 min
#define PRESSURE_ACCURACY_THRESHOLD		30
#define MAX_ALIGNING_TRIES				7
#define MAX_BAD_PRESSURE_TICKS		2

#define SETTINGS_FLASH_PAGE_ADDR	0x0801F800

